### ISSUE TITLE
loading meshes

### ISSUE THREAD

**Issue by Dakota5488** [BeamNG/vscode-jbeam-editor#1]
been trying to figure out a way to actually load meshes in the editor view, but the 3d meshes section in settings remain blank. extension isnt warning me that i need to open from "root" (im assuming this means the beamng install directory) so im a little confused on what im supposed to do here

**Comment by lonewolf0708** [comment]
I think it means the root of your project folder. So, for example, you're working on a vehicle named Gavril Grasshopper and want to visualize the parts in VS Code, you'd load the root folder containing the subfolders as a workspace. (CTRL+K CTRL+O by default) 

In the example image below, I am opening the t-80 tank mod root folder.
![image](https://github.com/BeamNG/vscode-jbeam-editor/assets/51030924/3e7e0e8c-8fd6-498c-ac57-cd83c32faa0c)


Then, when you select a part from the file tree on the left, the jbeam will be visible in the 3d view
![image](https://github.com/BeamNG/vscode-jbeam-editor/assets/51030924/669c06f2-0d0b-4e35-89c5-9882d65df274)

**Comment by angelo234** [comment]
Currently to view them, you must click on the JBeam file's "flexbodies" section with your cursor.
