### ISSUE TITLE
node variable maths 3D view position

### ISSUE THREAD

**Issue by fillman86** [BeamNG/vscode-jbeam-editor#10]
not a big issue but if you use maths on a node's position, it defaults to 0

here you'll see that there's maths on the y coordinate for fxl3 and fxr3, and it defaults to 0
![image](https://github.com/user-attachments/assets/81cf782f-40e2-4d01-8d46-6a14a408cb7d)

I feel that this might be a really tough issue to fix, and most people don't have this use case, so I'd understand this not being fixed

**Comment by angelo234** [comment]
Not really possible to solve this, since the editor only works on a part basis and not on an imported vehicle .pc file basis.

**Comment by angelo234** [comment]
The Blender JBeam Editor allows you to import .pc files though
