### ISSUE TITLE
inconsistent colouring

### ISSUE THREAD

**Issue by fillman86** [BeamNG/vscode-jbeam-editor#7]
I didn't notice it right away, but now I'm noticing that there's massive inconsistencies with the colouring. Not a big issue, but worth bringing up

here's a small but clear example
![image](https://github.com/BeamNG/vscode-jbeam-editor/assets/174102037/66e50c78-85d4-44a2-b33f-b4f013958f63)

**Comment by tdev** [comment]
uhh, that's weird, I'll have a look!

Thanks for caring - I really appreciate :)

**Comment by tdev** [comment]
I got around to test this finally, and its a syntax problem on above jbeam - there is a comma after the `flexbodies` section:

![Code_iBKC1ns77K](https://github.com/user-attachments/assets/3a8aa1d6-85f3-4b66-9126-4f868c418d2b)
