### ISSUE TITLE
multiple inline option mistake isnt highlighted (it didnt work ingame(4 month ago))

### ISSUE THREAD

**Issue by Please-Pick-a-Name** [BeamNG/vscode-jbeam-editor#9]
example of the mistake:
```json
    "slots": [
        ["type", "default", "description"],
        ["my_slot", "my_part", "My Slot", {"nodeOffset":{"x":0,"y":1,"z":2}}, {"coreSlot":true}],
    ],
```
the nodeOffset and coreSlot is seprated into 2 inline option dict, which the plugin doesnt catch, and the game couldnt handle it properly (understandably)

**Comment by Please-Pick-a-Name** [comment]
nvm, it does catch it, the plugin didnt refresh? when i did my replication test? now it notices it
my bad :(

**Comment by tdev** [comment]
Thanks for reporting a potential issue, glad it's not a bug in the end :)
